# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'throw.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1055, 857)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setContentsMargins(-1, -1, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.min_Button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.min_Button.sizePolicy().hasHeightForWidth())
        self.min_Button.setSizePolicy(sizePolicy)
        self.min_Button.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.min_Button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/back/back_img/最小化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.min_Button.setIcon(icon)
        self.min_Button.setObjectName("min_Button")
        self.horizontalLayout_2.addWidget(self.min_Button)
        self.max_Button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.max_Button.sizePolicy().hasHeightForWidth())
        self.max_Button.setSizePolicy(sizePolicy)
        self.max_Button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/back/back_img/最大化.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.max_Button.setIcon(icon1)
        self.max_Button.setObjectName("max_Button")
        self.horizontalLayout_2.addWidget(self.max_Button)
        self.close_Button = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_Button.sizePolicy().hasHeightForWidth())
        self.close_Button.setSizePolicy(sizePolicy)
        self.close_Button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/back/back_img/关闭.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_Button.setIcon(icon2)
        self.close_Button.setObjectName("close_Button")
        self.horizontalLayout_2.addWidget(self.close_Button)
        self.horizontalLayout_2.setStretch(0, 18)
        self.horizontalLayout_2.setStretch(1, 6)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.imput_choose_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        self.imput_choose_label.setFont(font)
        self.imput_choose_label.setObjectName("imput_choose_label")
        self.horizontalLayout.addWidget(self.imput_choose_label)
        self.videoButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        self.videoButton.setFont(font)
        self.videoButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/back/back_img/文件.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.videoButton.setIcon(icon3)
        self.videoButton.setObjectName("videoButton")
        self.horizontalLayout.addWidget(self.videoButton)
        self.camButton = QtWidgets.QPushButton(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        self.camButton.setFont(font)
        self.camButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/back/back_img/摄像头关.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.camButton.setIcon(icon4)
        self.camButton.setObjectName("camButton")
        self.horizontalLayout.addWidget(self.camButton)
        self.rtspButton = QtWidgets.QPushButton(self.groupBox)
        self.rtspButton.setEnabled(True)
        self.rtspButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/back/back_img/网络系统.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rtspButton.setIcon(icon5)
        self.rtspButton.setObjectName("rtspButton")
        self.horizontalLayout.addWidget(self.rtspButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.bg_choose_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        self.bg_choose_label.setFont(font)
        self.bg_choose_label.setObjectName("bg_choose_label")
        self.horizontalLayout.addWidget(self.bg_choose_label)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.FPS_label = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("Adobe Devanagari")
        font.setPointSize(11)
        self.FPS_label.setFont(font)
        self.FPS_label.setObjectName("FPS_label")
        self.horizontalLayout.addWidget(self.FPS_label)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.horizontalLayout.setStretch(5, 1)
        self.horizontalLayout.setStretch(6, 2)
        self.horizontalLayout.setStretch(7, 1)
        self.horizontalLayout.setStretch(8, 4)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.time_labe = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.time_labe.setFont(font)
        self.time_labe.setObjectName("time_labe")
        self.horizontalLayout_10.addWidget(self.time_labe)
        self.time_spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.time_spinBox.setObjectName("time_spinBox")
        self.horizontalLayout_10.addWidget(self.time_spinBox)
        self.time_horizontalSlider = QtWidgets.QSlider(self.groupBox)
        self.time_horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.time_horizontalSlider.setObjectName("time_horizontalSlider")
        self.horizontalLayout_10.addWidget(self.time_horizontalSlider)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem3)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 1)
        self.horizontalLayout_10.setStretch(2, 5)
        self.horizontalLayout_10.setStretch(3, 13)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.dete_out_label = QtWidgets.QLabel(self.groupBox)
        self.dete_out_label.setAutoFillBackground(True)
        self.dete_out_label.setStyleSheet("")
        self.dete_out_label.setText("")
        self.dete_out_label.setObjectName("dete_out_label")
        self.horizontalLayout_3.addWidget(self.dete_out_label)
        self.raw_label = QtWidgets.QLabel(self.groupBox)
        self.raw_label.setStyleSheet("")
        self.raw_label.setText("")
        self.raw_label.setObjectName("raw_label")
        self.horizontalLayout_3.addWidget(self.raw_label)
        self.horizontalLayout_3.setStretch(0, 1)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.play_pause_Button = QtWidgets.QPushButton(self.groupBox)
        self.play_pause_Button.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/back/back_img/赞停.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.play_pause_Button.setIcon(icon6)
        self.play_pause_Button.setObjectName("play_pause_Button")
        self.horizontalLayout_4.addWidget(self.play_pause_Button)
        self.progressBar = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.stop_Button = QtWidgets.QPushButton(self.groupBox)
        self.stop_Button.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/back/back_img/停止.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_Button.setIcon(icon7)
        self.stop_Button.setObjectName("stop_Button")
        self.horizontalLayout_4.addWidget(self.stop_Button)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 3)
        self.verticalLayout.setStretch(2, 2)
        self.verticalLayout.setStretch(3, 30)
        self.verticalLayout.setStretch(4, 2)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "高空抛物检测系统"))
        self.label.setText(_translate("MainWindow", "高空抛物检测系统"))
        self.imput_choose_label.setText(_translate("MainWindow", "输入选择"))
        self.bg_choose_label.setText(_translate("MainWindow", "背景模型选择"))
        self.FPS_label.setText(_translate("MainWindow", "FPS："))
        self.time_labe.setText(_translate("MainWindow", "保存时间"))

import back_img_rc
